///题库data
var requestData = {
    question_bank:[
        {
            title:"宝宝穿纸尿裤红PP应该怎么办",
            keys:[
                {content:"立马更换纸尿裤品牌",isRight:false},
                {content:"清洁PP",isRight:false},
                {content:"清理PP，轻轻蘸干或晾干，擦上护臀霜，穿上纸尿裤并及时更换",isRight:true},
                {content:"清理PP，擦上护臀霜",isRight:false}
            ],
            explain:{caption:"选购及使用纸尿裤全攻略",href:"http://www.8mbang.com/?q=article%2Fshow&id=42976",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"C",
            isAnswer:false

        },
        {
            title:"母乳喂养的宝宝添加辅食的最佳时间为",
            keys:[
                {content:"4个月",isRight:false},
                {content:"6个月",isRight:true},
                {content:"3个月",isRight:false},
                {content:"7个月",isRight:false}
            ],
            explain:{caption:"宝宝什么时间开始添加辅食最好,怎么添加？",href:"http://www.8mbang.com/?q=article%2Fshow&id=57041",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"B",
            isAnswer:false

        },
        {
            title:"宝宝三天没有大便，以下处理方法错误的是",
            keys:[
                {content:"用开塞露帮助宝宝排便",isRight:true},
                {content:"多喝水帮宝宝缓解上火症状",isRight:false},
                {content:"按摩宝宝肚子助消化",isRight:false},
                {content:"母乳喂养妈妈的调整饮食",isRight:false}
            ],
            explain:{caption:"宝宝便秘常是“吃”惹的祸",href:"http://www.8mbang.com/?q=article%2Fshow&id=49056",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"A",
            isAnswer:false
        },
        {
            title:"母乳妈妈奶水不够，应该",
            keys:[
                {content:"尝试古法下奶汤下奶食物",isRight:false},
                {content:"大量补充高蛋白质食品",isRight:false},
                {content:"放弃母乳喂养",isRight:false},
                {content:"让宝宝多吸吮，清淡饮食",isRight:true}
            ],
            explain:{caption:"对付奶水不足的开奶12法",href:"http://www.8mbang.com/?q=article%2Fshow&id=49874",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"D",
            isAnswer:false
        },
        {
            title:"关于补钙以下说法错误的是",
            keys:[
                {content:"宝宝出生2周后要及时补充鱼肝油",isRight:false},
                {content:"多晒太阳预防宝宝缺钙",isRight:false},
                {content:"纯母乳喂养的宝宝6个月前一般不需额外补充钙剂",isRight:false},
                {content:"宝宝出生后就要及时补钙",isRight:true}
            ],
            explain:{caption:"宝宝补钙3大方法4项注意",href:"http://www.8mbang.com/?q=article%2Fshow&id=49331",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"D",
            isAnswer:false
        },
        {
            title:"测试宝宝穿盖合适最有效的方法是",
            keys:[
                {content:"摸宝宝手脚，冷热适中",isRight:false},
                {content:"看宝宝脸色，颜色红润",isRight:false},
                {content:"摸宝宝后脖子，温热无汗",isRight:true},
                {content:"以大人的穿盖为标准",isRight:false}
            ],
            explain:{caption:"判断孩子冷热最好摸后脖子",href:"http://www.8mbang.com/?q=article%2Fshow&id=57030",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"C",
            isAnswer:false
        },
        {
            title:"关于奶粉冲调以下错误的说法是",
            keys:[
                {content:"先放水，再放奶粉",isRight:false},
                {content:"水温控制在37度左右为最佳",isRight:false},
                {content:"米粉和奶粉最好不要混合冲调",isRight:false},
                {content:"用矿泉水冲调奶粉既安全，营养又高",isRight:true}
            ],
            explain:{caption:"长期矿泉水冲奶粉会加重肾脏负担",href:"http://www.8mbang.com/?q=article%2Fshow&id=36816",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"D",
            isAnswer:false
        },
        {
            title:"宝宝食物中添加调味料最好在",
            keys:[
                {content:"添加辅食之后",isRight:false},
                {content:"没有特别的规定",isRight:false},
                {content:"1岁以后",isRight:true},
                {content:"10个月后",isRight:false}
            ],
            explain:{caption:"婴幼儿调味品应该怎么吃",href:"http://www.8mbang.com/?q=article%2Fshow&id=48996",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"C",
            isAnswer:false
        },
        {
            title:"清理宝宝鼻屎的方法有",
            keys:[
                {content:"用温毛巾热敷宝宝鼻根处",isRight:false},
                {content:"在宝宝鼻孔处滴一点母乳",isRight:false},
                {content:"用吸鼻器帮宝宝排出",isRight:false},
                {content:"以上都可以",isRight:true}
            ],
            explain:{caption:"清理宝宝鼻屎鼻涕也有技巧",href:"http://www.8mbang.com/?q=article%2Fshow&id=10891",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"D",
            isAnswer:false
        },
        {
            title:"宝宝从几个月开始可以开始竖抱",
            keys:[
                {content:"出生后就可以",isRight:false},
                {content:"3个月",isRight:true},
                {content:"7个月",isRight:false},
                {content:"9个月",isRight:false}
            ],
            explain:{caption:"3个月内的宝宝不能竖抱",href:"http://www.8mbang.com/?q=article%2Fshow&id=32975",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"B",
            isAnswer:false
        },
        {
            title:"以下哪种吐奶需要及时就医",
            keys:[
                {content:"吃完马上就吐",isRight:false},
                {content:"呈喷射状的吐奶",isRight:true},
                {content:"拍了嗝还是吐",isRight:false},
                {content:"吃奶一个小时后吐",isRight:false}
            ],
            explain:{caption:"宝宝吐奶的原因与应对招数",href:"http://www.8mbang.com/?q=article%2Fshow&id=49288",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"B",
            isAnswer:false
        },
        {
            title:"宝宝洗澡的最佳室温和水温是",
            keys:[
                {content:"室温26-28度，水温37-42度",isRight:true},
                {content:"室温23-24度，水温30-32度",isRight:false},
                {content:"室温26-28度，水温30-32度",isRight:false},
                {content:"室温23-24度，水温37-42度",isRight:false}
            ],
            explain:{caption:"帮宝宝洗澡妈妈别闯五大误区",href:"http://www.8mbang.com/?q=article%2Fshow&id=16884",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"A",
            isAnswer:false
        },
        {
            title:"关于宝宝饮食，以下说法正确的是",
            keys:[
                {content:"奶粉越浓，营养成分越多",isRight:false},
                {content:"不喝开水可以喝果汁代替",isRight:false},
                {content:"辅食添加，最好由细到粗，由稀到稠",isRight:true},
                {content:"不爱吃饭，有营养的点心也可以",isRight:false}
            ],
            explain:{caption:"掌握宝宝辅食添加八项原则",href:"http://www.8mbang.com/?q=article%2Fshow&id=49085",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"C",
            isAnswer:false
        },
        {
            title:"关于物理降温法，哪种方法是错误的",
            keys:[
                {content:"用温水擦拭宝宝脖子，大腿根及腋窝",isRight:false},
                {content:"宝宝发烧可用酒精擦拭降温",isRight:true},
                {content:"38.5度以下最好先用物理降温法",isRight:false},
                {content:"使用退热贴",isRight:false}
            ],
            explain:{caption:"物理降温的方法有哪些",href:"http://www.8mbang.com/?q=article%2Fshow&id=37624",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"B",
            isAnswer:false
        },
        {
            title:"关于选择奶粉，最重要的原则是",
            keys:[
                {content:"进口奶粉，奶源好",isRight:false},
                {content:"口碑好，朋友的宝宝都在吃",isRight:false},
                {content:"适合宝宝口味及体质",isRight:true},
                {content:"价钱高，添加营养成分多",isRight:false}
            ],
            explain:{caption:"根据婴儿的发育选择奶粉",href:"http://www.8mbang.com/?q=article%2Fshow&id=25153",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"C",
            isAnswer:false
        },
        {
            title:"关于使用抗生素，以下说法正确的是",
            keys:[
                {content:"宝宝不能使用抗生素，会产生依赖",isRight:false},
                {content:"及时使用抗生素，生病会影响宝宝发育",isRight:false},
                {content:"不滥用抗生素，病情严重时需使用抗生素",isRight:true},
                {content:"宝宝发烧，有炎症时，妈妈可给宝宝口服抗生素",isRight:false}
            ],
            explain:{caption:"宝宝生病使用抗生素要慎重",href:"http://www.8mbang.com/?q=article%2Fshow&id=42756",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"C",
            isAnswer:false
        },
        {
            title:"以下哪种情况，不会导致宝宝消化不良",
            keys:[
                {content:"母乳妈妈饮食油腻",isRight:false},
                {content:"更换奶粉",isRight:false},
                {content:"过早添加辅食",isRight:false},
                {content:"按需喂养",isRight:true}
            ],
            explain:{caption:"宝宝消化不良专家为你支招",href:"http://www.8mbang.com/?q=article%2Fshow&id=18033",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"D",
            isAnswer:false
        },
        {
            title:"哪些情况不会影响宝宝夜间睡眠",
            keys:[
                {content:"晚餐过饱或吃了不易消化的食物",isRight:false},
                {content:"白天活动多，消耗宝宝多余精力",isRight:true},
                {content:"睡前兴奋，玩得太开心",isRight:false},
                {content:"白天睡得多",isRight:false}
            ],
            explain:{caption:"宝宝健康睡眠的三大规矩",href:"http://www.8mbang.com/?q=article%2Fshow&id=56681",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"B",
            isAnswer:false
        },
        {
            title:"关于宝宝学走路，以下说法正确的是",
            keys:[
                {content:"会站就可以教宝宝走路",isRight:false},
                {content:"3个月后就可以扶着宝宝腋下学习走路",isRight:false},
                {content:"最好1岁以后再学习走路",isRight:true},
                {content:"走路晚就是缺钙",isRight:false}
            ],
            explain:{caption:"宝宝什么时候学走路好呢？",href:"http://www.8mbang.com/?q=article%2Fshow&id=36197",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"C",
            isAnswer:false
        },
        {
            title:"关于宝宝学说话，以下说法正确的是",
            keys:[
                {content:"越早说话越聪明",isRight:false},
                {content:"说话是人的天生本领，不教也能学会",isRight:false},
                {content:"到月龄不说话，需要给宝宝挑舌系带",isRight:false},
                {content:"教宝宝说话应该多跟宝宝交流，多听有韵律的儿歌",isRight:true}
            ],
            explain:{caption:"教宝宝学说话的6个妙招",href:"http://www.8mbang.com/?q=article%2Fshow&id=26624",wxcode:"42976"},
            tip:{},
            result:false,
            answer:"D",
            isAnswer:false

        }
    ]
};